<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <LangVersion>latest</LangVersion>
	  <OutputPath>..\bin\</OutputPath>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

	<PropertyGroup>
		<!-- Redirect AssemblyAttributes.cs so each project has its own -->
		<TargetFrameworkMonikerAssemblyAttributesPath>$(IntermediateOutputPath)$(MSBuildProjectName).AssemblyAttributes.cs</TargetFrameworkMonikerAssemblyAttributesPath>
		<!-- Avoid duplicate TargetFrameworkAttribute -->
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
	</PropertyGroup>
	<ItemGroup>
		<!-- Prevent duplicate 'Compile' inclusion of the generated AssemblyAttributes.cs -->
		<Compile Remove="$(IntermediateOutputPath)$(MSBuildProjectName).AssemblyAttributes.cs" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiGi.WebTracker.UI\DiGi.WebTracker.UI.csproj" />
    <ProjectReference Include="..\DiGi.WebTracker\DiGi.WebTracker.csproj" />
  </ItemGroup>

</Project>
