<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <LangVersion>latest</LangVersion>
	  <OutputPath>..\bin\</OutputPath>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	  <Nullable>enable</Nullable>
  </PropertyGroup>

	<PropertyGroup>
		<!-- Redirect AssemblyAttributes.cs so each project has its own -->
		<TargetFrameworkMonikerAssemblyAttributesPath>$(IntermediateOutputPath)$(MSBuildProjectName).AssemblyAttributes.cs</TargetFrameworkMonikerAssemblyAttributesPath>
		<!-- Avoid duplicate TargetFrameworkAttribute -->
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
	</PropertyGroup>
	<ItemGroup>
		<!-- Prevent duplicate 'Compile' inclusion of the generated AssemblyAttributes.cs -->
		<Compile Remove="$(IntermediateOutputPath)$(MSBuildProjectName).AssemblyAttributes.cs" />
	</ItemGroup>

</Project>
